### ISSUE TITLE
Alias and _resource on menu item.

### ISSUE THREAD

**Issue by Biromain** [ventoviro/windwalker-joomla-rad#205]
Hello, i don't know if it's a bug or misunderstand.

https://github.com/ventoviro/windwalker-joomla-rad/blob/staging/src/Router/RadRoute.php#L229

I need to unset `_resource` and `alias`
```php
$data['view'] = null;
$data['id'] = null;
$data['_resource'] = null;
$data['alias'] = null;
```

If he found menu item id, he generate menuIdPathway/(id)-analias.

**Comment by asika32764** [comment]
How do you build this route? Have you add route profiles in `routing.yml`?

**Comment by Biromain** [comment]
I build route like that 
```php
// Link
$item->link = Route::_('category', array(
  'id'    => $item->id,
  'alias' => $item->alias,
  'view' => 'category'
));
```

```yml
category:
  pattern: "categorie/(id)-(alias)"
  view: "category"
  requirements:
      id: \d+
```
